spring.application.name=best-price-book-store

logging.level.web=DEBUG
logging.pattern.console=%d{HH:mm:ss} [%15thread] %msg%n

spring.threads.virtual.enabled=true

#max socket connections that can be handled by Tomcat
server.tomcat.max-connections=50000

book.store.base.urls={'Wonder Book Store':'http://localhost:8081','Mascot Book Store':'http://localhost:8082'}



allowance.per.leave=5000
