spring.application.name=virtualthreads-demo

logging.level.web=DEBUG
logging.pattern.console=%d{HH:mm:ss} [%15thread] %msg%n

spring.threads.virtual.enabled=true

#max socket connections that can be handled by Tomcat
server.tomcat.max-connections=50000